### ISSUE TITLE
Cannot create sheet when already exists

### ISSUE THREAD

**Issue by bcvanmeurs** [michie1/bc#30]
Error occurs when another computer has already incremented BC number and BC number of current computer is behind.
Script tries to create new sheet, while it was already created.

```bash
python wtosbc/main.py
Session started
Token retrieved:  8e18bba94fb4a51ef3bcecf3a66fbd344643ee52
Logged in
start
increment bc number
reset PA state
create next sheet
Load Google credentials
Traceback (most recent call last):
  File "wtosbc/main.py", line 60, in <module>
    go()
  File "wtosbc/main.py", line 29, in go
    orders = wtos.get_orders(bc_number, posts)
  File "/Users/bramvanmeurs/repos/bc/wtosbc/wtos.py", line 71, in get_orders
    create_next_sheet(int(bc_number) + 1)
  File "/Users/bramvanmeurs/repos/bc/wtosbc/wtos.py", line 29, in create_next_sheet
    spreadsheet.create_sheet(number)
  File "/Users/bramvanmeurs/repos/bc/wtosbc/spreadsheet.py", line 24, in create_sheet
    sh.add_worksheet(title="BC" + str(bc_number), rows="1", cols="1")
  File "/Users/bramvanmeurs/repos/bc/venv/lib/python3.7/site-packages/gspread/models.py", line 272, in add_worksheet
    data = self.batch_update(body)
  File "/Users/bramvanmeurs/repos/bc/venv/lib/python3.7/site-packages/gspread/models.py", line 100, in batch_update
    json=body
  File "/Users/bramvanmeurs/repos/bc/venv/lib/python3.7/site-packages/gspread/client.py", line 79, in request
    raise APIError(response)
gspread.exceptions.APIError: {
  "error": {
    "code": 400,
    "message": "Invalid requests[0].addSheet: A sheet with the name \"BC194\" already exists. Please enter another name.",
    "status": "INVALID_ARGUMENT"
  }
}
```
The second time the script is used PA state is correct and continues normally.
```bash
python wtosbc/main.py
Session started
Token retrieved:  1cf1c8775a820a63b7ce3fbe901b3d1cacead3a5
Logged in
start
Orders loaded
Cart cleared
Item/type does not exist?
list index out of range
{'id': '58034', 'name': b'Shimano SM-RT800 Center Lock Brake Rotor for Ultegra', 'qty': '1', 'pa': '', 'type': '', 'price': 0, 'type_id': '', 'token': ''}
Orders added to cart
voucher_token retrieved:  _VDsXTRKKuqq-WUg9B3ubtOge-1AAYzF95iGtPRHm2I
Price alerts added
Removed items from cart
Load Google credentials
Spreadsheet loaded
Orders added to spreadsheet
Finished
```

**Comment by bcvanmeurs** [comment]
Suggestie is om het spreadsheet script te laten checken of de nieuwe BC sheet al bestaat.
